Pool threads
mariatrunina/spbu-python-course pull request #7
Opened 2024-10-20 07:53 UTC by mariatrunina

Я реализовала паттерн "пул потоков". Добавила тесты к коду и написала docstrings. А также выполнила доп задание.

2024-10-20 08:23 UTC, Krekep requested changes
Не выполнены формальные требования к PR (не проходят CI тесты)

2024-10-21 08:53 UTC, Krekep requested changes
Необходимы исправления

2024-10-21 08:53 UTC, Krekep commented on project/threads.py
> +        self.tasks: queue.Queue[Callable] = queue.Queue()  # Добавлена аннотация типа
Этот класс реализует в себе методы для работы с потоками. Из пакетов для работы с многопоточностью по условию задачи разрешён только `threading`

2024-10-21 08:53 UTC, Krekep commented on project/threads.py
> +                print(f"Task completed with result: {result}")
Опять же, лучше по умолчанию не выводить

2024-10-21 08:53 UTC, Krekep commented on project/threads.py
> +            try:
`try/except` работает сильно медленнее, чем `if`, в случае если вызывается исключение. А похоже, что в данном коде оно будет вызываться часто

2024-10-21 08:53 UTC, Krekep commented on project/threads.py
> +    return random.randint(1, 100)
Это в тесты, нет? Или в примеры?

2024-10-21 08:53 UTC, Krekep commented on project/threads.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Чем обоснован выбор `ThreadPoolExecutor` для этой задачи?

2024-10-21 08:53 UTC, Krekep commented on project/threads.py
> +        future = executor.submit(cartesian_product_sum, list1, list2)
Вы отправляете одну задачу, которая будет выполняться одним потоком, нет?

2024-10-21 08:53 UTC, Krekep commented on tests/test_threads.py
> +    assert len(thread_pool.threads) == thread_pool.pool_size
Лучше проверять через `threading.active_count()`

2024-10-21 08:53 UTC, Krekep commented on tests/test_threads.py
> +    assert result == 63
Это всё-таки две разных задачи. Разнесите их по разным файлам (как исходники, так и тесты)

2024-10-21 08:53 UTC, Krekep commented on tests/test_threads.py
> +def test_cartesian_product_sum():
Круто, что корректно складываются числа, но хочется ещё посмотреть на сравнительное время работы

2024-10-22 08:21 UTC, Krekep commented on tests/test_threads.py
> +def test_cartesian_product_sum():
Ладно, скорее всего я был неправ, давая такое задание. Для более тяжёлых функций, чем `sum` задание имело бы смысл, но в с учётом того, что `sum` использует сишную реализацию, оверхед на копирование массивов между процессами и их синхронизацию сильно больше, чем выигрыш от их использования в такой простой задаче. Так что окей, можете не добавлять такой тест. Либо можете добавить более тяжёловесную функцию (добавить, к примеру косинусы, синусы, корни или, к примеру, сортировку сделать) и показать, что с процессами она будет быстрее
Также можете почитать [этот тред](https://www.reddit.com/r/Python/comments/5tfm64/multiprocessing_parallel_sum_slower_than_serial/) и [вот этот](https://stackoverflow.com/questions/42074501/python-concurrent-futures-processpoolexecutor-performance-of-submit-vs-map)

2024-10-22 08:24 UTC, Krekep commented on project/threads.py
> +    return random.randint(1, 100)
Возможно это звучало грубо, поэтому на всякий случай уточню, что тут не было негатива в Вашу сторону

2024-10-24 14:11 UTC, mariatrunina commented on project/threads.py
> +        self.tasks: queue.Queue[Callable] = queue.Queue()  # Добавлена аннотация типа
Исправила

2024-10-24 14:11 UTC, mariatrunina commented on project/threads.py
> +    return random.randint(1, 100)
Я переместила его

2024-10-25 08:23 UTC, Krekep approved these changes
Основная задача зачтена, подзадача нет. 
Также Вы не выполнили формальные требования к оформлению пулл-реквеста (не ответили на замечания)

2024-10-25 08:23 UTC, Krekep commented on project/concurent_futures.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
`ThreadPool`  не подходит для этой задачи, т.к. из-за GIL в один момент времени может исполняться только один поток. Таким образом суммы вычисляется не параллельно

2024-10-25 08:23 UTC, Krekep commented on project/concurent_futures.py
> +        future = executor.submit(cartesian_product_sum, list1, list2)
Вы посылаете в пул одну задачу --- просуммировать два массива целиком. Для параллельного выполнения Вам необходимо было, к примеру,  разделить массивы на подчасти, просуммировать их отдельно и затем просуммировать результат подзадач

2024-10-26 13:47 UTC, merged